name: Link check
on:
  schedule: [ { cron: "15 2 * * 1" } ] # weekly
  workflow_dispatch:
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-mail './**/*.md' './**/*.html'
      - name: Create issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Broken links detected"
          content-filepath: ./lychee/out.md
          labels: docs, broken-link
